name: intensify_surveillance_system

description: Intensify Surveillance System

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.3+2
  path_provider: ^2.0.14
  path: ^1.8.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter_tflite: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/